.storybook/config.js
.storybook/webpack.config.js
package-lock.json
package.json
stories/index.js
yarn.lock

+ *Added [storybook.js](https://storybook.js.org/) to our repo for interactive testing*
+ *Adjusted Jest testing settings to only collect coverage from relevant files*
Testing Done:
+ Jest testing passing

Added storybook to our repo

---

README.md

added badges
+ *Added badges for NPM, Travis-CI, and Codecov*

Added badges for Travis-CI, CodeCov, and NPM

---

.gitignore
package.json
src/lib/components/Example.scss
src/lib/components/SecondExample.scss
src/lib/index.js
src/styles/_colors.scss
yarn.lock

+ *Removed Material-UI and moved towards Semantic-UI*
+ *Added node-sass-chokidar to work with scss files*

Added semantic UI and removed Material UI

---

package-lock.json
package.json
yarn.lock

Closes #6
Testing Done:
+ Please squash your commits when possible (look [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) and [here](https://dgdgit.chop.edu/gist/GonzalezMA/41ceb5f58ffec0e7db3c87dbee72038b) for …

chore(package): update webpack-dev-server to version 2.9.7

---

src/demo/App.js
src/demo/components/Buttons.js
src/demo/components/Forms.js
src/demo/components/Icons.js
src/lib/index.js
src/lib/molecules/save-form-modal.js
src/lib/molecules/save-form-modal.test.js
src/lib/molecules/save-form.js
src/lib/molecules/save-form.test.js

+ *Added Form/Modal*
Testing Done:
+ Tests are included.
+ Tests are missing for testing Modal form input.  This is currently a limitation of enzyme/jest.  See [this](https://github.com/airbnb/enzyme/blob/master/docs/common-issues.md#testing-third-party-libraries)

Added Form/Modal

---

.travis.yml

+ *Added GreenKeeper lock to update yarn-lock.json file*

Added GreenKeeper Lock file update

---

.travis.yml

+ *GreenKeeper lock file was failing see [here](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98), therefore removed it for the time being*

Replace yarn with npm in .travis.yml.   NPM seems more stable in Travis for now

---

src/lib/constants/genomics-urls.js
src/lib/index.js
src/lib/utils/urlBuilders.js
src/lib/utils/urlBuilders.test.js

+ *#40 - Added functions that build commonly accessed genomics URLs*
Testing Done:
+ Unittests are included

Resolved #40

---

src/lib/utils/urlBuilders.js
src/lib/utils/urlBuilders.test.js

+ Wrong Namespace imported. Fixed #47

fixed typos in urlBuilders.js #47

---

src/demo/components/BigDataTableExample.js
src/demo/components/TableCellExamples.js
src/lib/atoms/table-cells/gene-cell.js
src/lib/atoms/table-cells/gene-cell.test.js
src/lib/atoms/table-cells/public-resources-evidence-cell.test.js
src/lib/atoms/table-cells/transcript-cell.js
src/lib/atoms/table-cells/transcript-cell.test.js
src/lib/atoms/table-cells/turn-around-time-cell.test.js
src/lib/index.js
src/lib/molecules/table-columns/gene-column.js
src/lib/molecules/table-columns/gene-column.test.js
src/lib/molecules/table-columns/interpretation-column.test.js
src/lib/molecules/table-columns/transcript-column.js
src/lib/molecules/table-columns/transcript-column.test.js

+ *Gene Cell/Column*
+ *Transcript Cell/Column*
Testing Done:
+ Unittests are included

Gene/Transcript Cell and Column

---

src/demo/components/BigDataTableExample.js
src/demo/components/TableCellExamples.js
src/lib/atoms/table-cells/date-cell.js
src/lib/atoms/table-cells/date-cell.test.js
src/lib/atoms/table-cells/link-cell.js
src/lib/atoms/table-cells/link-cell.test.js
src/lib/atoms/table-cells/status-cell.js
src/lib/atoms/table-cells/status-cell.test.js
src/lib/index.js
src/lib/molecules/table-columns/date-column.js
src/lib/molecules/table-columns/date-column.test.js
src/lib/molecules/table-columns/status-column.js
src/lib/molecules/table-columns/status-column.test.js
src/stylesheets/partials/tables.scss

added StatusColumn to Example
+ *#41*
Testing Done:
+ Unittests are included

Resolved #41

---

src/demo/components/FixedDataTableExample.js
src/lib/molecules/tables/fixed-data-table.js
src/lib/molecules/tables/fixed-data-table.test.js

+ *#79*
+ *Now we can pass in a prop `fixedColumns` that will fix columns on the left.  When using this you can have a table and handle this dynamically or just pass in an array*

Resolved #79

---

src/demo/components/BigDataTableExample.js
src/demo/components/Buttons.js
src/demo/components/Icons.js
src/demo/components/ProgressBars.js
src/lib/atoms/table-cells/checkbox-cell.js
src/lib/atoms/table-cells/date-cell.js
src/lib/atoms/table-cells/gene-cell.js
src/lib/atoms/table-cells/interpretation-cell.js
src/lib/atoms/table-cells/link-cell.js
src/lib/atoms/table-cells/molecular-consequence-cell.js
src/lib/atoms/table-cells/public-resources-evidence-cell.js
src/lib/atoms/table-cells/sex-cell.js
src/lib/atoms/table-cells/status-cell.js
src/lib/atoms/table-cells/text-cell.js
src/lib/atoms/table-cells/transcript-cell.js
src/lib/atoms/table-cells/turn-around-time-cell.js
src/lib/molecules/table-columns/checkbox-column.js
src/lib/molecules/table-columns/checkbox-column.test.js

+ *There were some props that were missing or being passed incorrectly, causing console errors.  These have been corrected*

Fixed issues that were causing console warnings

---

docs/Columns.md
docs/FixedDataTable.md
docs/FixedDataTableCells.md

Updated documentation to be accurate and account for the latest features

updated documentation

---

package.json

chore(package): update @storybook/react to version 3.3.2

---

package.json

chore(package): update @storybook/addon-links to version 3.3.2

---

package.json

chore(package): update @storybook/addon-actions to version 3.3.2

---

package-lock.json
yarn.lock

updated lock files

---

src/demo/components/LoginFormExample.jsx

Fixed some warnings that were being issued by the demo app

Fixed errors for LoginForm

---

package.json

chore(package): update jest to version 22.1.3

---

src/lib/molecules/menus/navbar.js
src/lib/molecules/menus/navbar.test.js

+ *#162*
Testing Done:
+ Unittests were updated and passing

Resolved #162 - Navbar activeItem is handled via Props instead of state

---

src/lib/atoms/buttons/ExportButton.js
src/lib/atoms/buttons/ExportButton.test.js

Resolved #158 - Update ExportButton

---

package.json

chore(package): update @storybook/react to version 3.3.12

---

package.json

chore(package): update @storybook/addon-actions to version 3.3.12

---

package.json
src/demo/components/Buttons.js
src/lib/atoms/buttons/ExportButton.test.js

fix(package): update react-csv to version 1.0.12

---

src/demo/components/Buttons.js
src/lib/atoms/buttons/ExportButton.js
src/lib/atoms/buttons/ExportButton.test.js

+ *Export button was not exporting appropriately*
Testing Done:
+ Unittests were updated

Fixed issue with export button

---

src/lib/molecules/tables/fixed-data-table.js

Add default maxHeight

---

package.json

chore(package): update file-loader to version 1.1.9

---

package.json
yarn.lock

Downgrade Semantic-UI-CSS

---

src/lib/molecules/menus/user-menu.js

Resolves #223
Fixes #223 
Testing Done:
No additional tests necessary 
All related tests are ✅

Change Log Out Path and Name

---

package.json

fix(package): update semantic-ui-react to version 0.79.1

---

package.json

chore(package): update node-sass to version 4.8.3

---

package.json

chore(package): update @storybook/react to version 3.4.2

---

package.json

chore(package): update @storybook/addon-actions to version 3.4.2

---

package.json

chore(package): update file-loader to version 1.1.11

---

package.json

chore(package): update sass-loader to version 7.0.3

---

package.json

fix(package): update semantic-ui-react to version 0.81.1

---

package.json

chore(package): update fs-extra to version 6.0.1

---

src/lib/atoms/table-cells/public-resources-evidence-cell.test.js
src/lib/constants/genomics-urls.js
src/lib/utils/urlBuilders.js
src/lib/utils/urlBuilders.test.js

+ *Added new URL builders for popular genomics resources*
Testing Done:
+ Unittests updated

Updated/Added new URL for genomics urls

---

src/demo/components/BigDataTableExample.js
src/demo/components/FixedDataTableExample.js
src/demo/components/TableCellExamples.js
src/lib/atoms/fixed-data-table-cells/gene-fixed-cell.js
src/lib/atoms/fixed-data-table-cells/gene-fixed-cell.test.js
src/lib/atoms/labels/basic-label.js
src/lib/atoms/labels/basic-label.test.js
src/lib/atoms/lists/genes-links-list.js
src/lib/atoms/lists/genes-links-list.test.js
src/lib/atoms/popups/genes-resources-popup.js
src/lib/atoms/popups/genes-resources-popup.test.js
src/lib/atoms/table-cells/gene-cell.js
src/lib/atoms/table-cells/gene-cell.test.js
src/lib/index.js
src/lib/molecules/table-columns/gene-column.js
src/lib/molecules/table-columns/gene-column.test.js
src/stylesheets/main.scss
src/stylesheets/partials/labels.scss

+ *Updated Gene table cells to be uniform and contain same popups with linkouts*
Testing Done:
+ Unittests updated

Updated Gene Cells to use uniform popups w/ link outs 

---

docs/CheckboxCell.md
docs/Columns.md
docs/GeneCell.md

+ *Updated documentation for v0.6.0*

Updated docs

---

package.json
yarn.lock

Greenkeeper/monorepo.babel7 7.1.2

---

package.json
yarn.lock

Greenkeeper/react scripts 2.0.4

---

package.json
yarn.lock

Greenkeeper/monorepo.enzyme 3.7.0

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 3.1.4

---

package.json
yarn.lock

Greenkeeper/react csv 1.0.18

---

package.json
yarn.lock

Updated deps for react-genomix

---

demo/src/components/Buttons.js
package.json
src/atoms/buttons/ExportButton.js
src/atoms/buttons/ExportButton.test.js

Issue 357 export

---

package.json
yarn.lock

Greenkeeper/babel preset react app 7.0.0

---

package.json

+ *added collect coverage to jest to fix codecov on travis builds*
Testing Done:
+ Unittests are passing
+ Codecov is now being uploaded correctly

added collect coverage to jest to fix codecov on travis builds

---

demo/src/index.js
package.json
src/hooks/use-form-input.js
src/hooks/use-local-storage.js
src/hooks/use-state-list.js
src/hooks/use-window-size.js
src/index.js
yarn.lock

+ *Added some commonly used custom hooks*

Added some commonly used custom hooks

---

package.json
yarn.lock

Greenkeeper/eslint 5.15.1

---

demo/src/components/FixedDataTableExample.js
package.json
src/tables/fixed-data-table.js
yarn.lock

added autosizer to fixed data table

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 3.6.1

---

package.json
yarn.lock

Greenkeeper/dotenv expand 5.1.0

---

package.json
yarn.lock

Greenkeeper/eslint plugin import 2.17.2

---

package.json
yarn.lock

Greenkeeper/semantic ui react 0.87.1

---

package.json
yarn.lock

Missing plugin for react-hooks has been added.

Added in ESLint plugin for react-hooks

---

src/hooks/index.js
src/hooks/use-interval.js
src/index.js

+ *Added a custom hook for using setInterval*
See [this](https://overreacted.io/making-setinterval-declarative-with-react-hooks/)

Added custom hook for useInterval

---

package.json
yarn.lock

Greenkeeper/fixed data table 2 0.8.26

---

package.json

chore(package): update enzyme-adapter-react-16 to version 1.13.2

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 3.10.1

---

src/hooks/use-local-storage.js

+ *#451 - allows `useLocalStorage` to use various data types*

Resolved #451 made useLocalStorage capable of using different data types

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 3.10.3

---

src/hooks/use-local-storage.js

Will update state if key changes
Also added eventListener so if any other tab updates localStorage, pages will reflect those changes as well.
Closes #463

Resolved #463 - Updated useLocalStorage

---

package.json

chore(package): update eslint-plugin-flowtype to version 3.12.1

---

package.json

chore(package): update @babel/core to version 7.5.5

---

package.json
yarn.lock

Greenkeeper/eslint plugin jsx a11y 6.2.3

---

demo/src/components/ProgressBars.js
src/progress-bars/turn-around-time-progress.js

- Fixes moment deprecation warning
- Related to https://github.research.chop.edu/DGD/nexus/issues/1328

Pass date format to dateFormatter

---

demo/src/components/InfiniteTableExample.js
demo/src/components/SelectionTableExample.js
demo/src/index.js
src/tables/basic-table.js
src/tables/selection-table.js

No need to `allChecked` prop. We can use the `data` prop from the `onChange` event to achieve same result

Selection Table improvement

---

demo/src/components/Table.js
src/tables/table.js

+ *#448*
Testing Done:
+ tests passing

[closes #448] - Drops support for storing column widths in localStorage

---

package.json

chore(package): update eslint-plugin-react-hooks to version 2.0.1

---

package.json

chore(package): update eslint-config-react-app to version 5.0.1

---

package.json

chore(package): update jest-resolve to version 24.9.0

---

package.json

chore(package): update @babel/core to version 7.6.0

---

package.json

fix(package): update react-base-table to version 1.8.0

---

src/tables/table.js

[closes #514] - render no data message when data.length === 0

---

package.json
yarn.lock

Greenkeeper/eslint plugin react 7.16.0

---

src/constants/genomics-urls.js
src/utils/urlBuilders.js
src/utils/urlBuilders.test.js

[Closes #545] Adds ClinGen URL

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 4.4.1

---

package.json

chore(package): update eslint-plugin-flowtype to version 4.5.2

---

package.json
yarn.lock

Greenkeeper/eslint 6.7.2

---

src/utils/getColor.js
src/utils/getColor.test.js

added colors for priority and gene validity

---

src/table-cell-renderers/label-cell.js
src/table-cell-renderers/label-cell.test.js

renders empty string if celldata is null

---

package.json

chore(package): update @babel/core to version 7.7.7

---

package.json
yarn.lock

Greenkeeper/eslint plugin import 2.19.1

---

package.json

chore(package): update @babel/core to version 7.8.0

---

src/constants/genomics-urls.js
src/utils/urlBuilders.js
src/utils/urlBuilders.test.js

Adds mouse genome database url

---

demo/src/components/ProgressBars.js
src/progress-bars/turn-around-time-progress.js
src/utils/getTurnAroundTimeDetails.js
src/utils/getTurnAroundTimeDetails.test.js

[closes 574] Turn Around Time calculation fixed

---

package.json
yarn.lock

Greenkeeper/prettier 2.0.5

---

package.json

chore(package): update babel-preset-react-app to version 9.1.2
